"""add mentor to users

Revision ID: edeb048e03c8
Revises: f780a0446dc6
Create Date: 2026-01-14 11:47:26.285746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edeb048e03c8'
down_revision: Union[str, Sequence[str], None] = 'f780a0446dc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mentor', sa.Text(), nullable=True, comment='user selected investment mentor'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mentor')
    # ### end Alembic commands ###
